show tables;

CREATE TABLE CUSTOMER (
 Customer_id INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(500) NOT NULL,
 Phone VARCHAR(12) NOT NULL,
 PRIMARY KEY (Customer_id,Phone));
 
 
CREATE TABLE OWNER (
 Owner_id INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(200) NOT NULL,
 Owner_type VARCHAR(10) NOT NULL,
 PRIMARY KEY ( Owner_id)
);

CREATE TABLE CAR (
 VehicleID INT NOT NULL AUTO_INCREMENT,
 OwnerID INT NOT NULL,
 Model VARCHAR(50) NOT NULL,
 Year INT,
 Color VARCHAR(10),
 Car_type VARCHAR(20) NOT NULL,
 Car_category VARCHAR(10) NOT NULL,
 PRIMARY KEY (VehicleID),
 FOREIGN KEY (OwnerID) REFERENCES OWNER (Owner_id) ON DELETE CASCADE
);

ALTER TABLE CAR AUTO_INCREMENT=1001;

CREATE TABLE AVAILABILITY (
 Vehicle_ID INT NOT NULL,
 Available_from DATE NOT NULL,
 Available_till DATE NOT NULL,
 FOREIGN KEY (Vehicle_ID) REFERENCES CAR (VehicleID) ON DELETE CASCADE
);

CREATE TABLE RATES (
 Vehicle_ID INT NOT NULL,
 Daily_rate INT NOT NULL,
 Weekly_rate INT NOT NULL,
 FOREIGN KEY (Vehicle_ID) REFERENCES CAR (VehicleID) ON DELETE CASCADE
);


CREATE TABLE RENTAL (
 Rental_id INT NOT NULL AUTO_INCREMENT,
 Customer_id INT NOT NULL,
 Vehicle_id INT NOT NULL,
 RentalType VARCHAR(10) NOT NULL,
 Location VARCHAR(20),
 Start_date DATE NOT NULL,
 NO_OF_WEEKS_DAYS INT NOT NULL,
 PAYMENT_DUE INT NOT NULL,
 PRIMARY KEY (Rental_id),
 FOREIGN KEY (Customer_id) REFERENCES CUSTOMER (Customer_id) ON DELETE CASCADE,
 FOREIGN KEY (Vehicle_id) REFERENCES CAR (VehicleID) ON DELETE CASCADE
);